services:
  orthanc:
    image: orthancteam/orthanc:25.2.0
    restart: unless-stopped
    ports:
      - "4242:4242" # DICOM port
      - "8042:8042" # UI
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./config/orthanc.json:/etc/orthanc/orthanc.json
    depends_on:
      - postgres

  postgres:
    image: postgres:17.4
    restart: unless-stopped
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:1.27.4
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - orthanc

volumes:
  postgres_data: