services:
  orthanc:
    image: orthancteam/orthanc
    restart: unless-stopped
    ports:
      - "4242:4242" # DICOM port
      - "8042:8042" # UI
    volumes:
      - ./config/orthanc.json:/etc/orthanc/orthanc.json
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: unless-stopped
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_DB: "dicom_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin123123"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - orthanc

volumes:
  postgres_data: