version: '3.9'
services:
  orthanc:
    image: orthancteam/orthanc
    container_name: orthanc
    ports:
      - "4242:4242" # DICOM port
      - "8042:8042" # UI
    volumes:
      - ./config/orthanc.json:/etc/orthanc/orthanc.json

  nginx:
    image: nginx:latest
    container_name: nginx-cors-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - orthanc